fixup! Process vendor init lib via soong config
Original change broke non-tegra targets that set a custom libinit.

error: device/nvidia/tegra-common/init/Android.bp:35:1: "init_tegra" depends on undefined module "//device/motorola/sm8250-common:libinit_moto_kona_vendor".

This gates init_tegra's sourcing the extra vendor lib on a tegra only
variable.

Change-Id: I45dbcd0ad6ecbbc50873379e7098f52d8ed1d5c2