Guard init_tegra static library for tegra only
Non-tegra targets that use a vendor libinit see an error like the
following when tegra-common is in the build tree:

error: device/nvidia/tegra-common/init/Android.bp:35:1: "init_tegra" depends on undefined module "//device/motorola/sm8250-common:libinit_moto_kona_vendor".

This gates init_tegra's sourcing the extra vendor lib on a tegra only
variable.

Fixes: 69d763b2b2b ("Process vendor init lib via soong config")
Change-Id: I45dbcd0ad6ecbbc50873379e7098f52d8ed1d5c2