Revert "tegra: add optional dolby HALs to matrix"
This reverts commit cb1429fc5e5e098e0668e5527f4e49b81119a106.

Reason:
```
ERROR: HIDL interface vendor.dolby.audio.measurement@1.0::ILatencyReporter is referenced in /system/etc/vintf/compatibility_matrix.device.xml, but there is no corresponding .hal definition associated with a hidl_interface module in this build. Typo?
HIDL interface vendor.dolby.ms12@1.2::IMs12 is referenced in /system/etc/vintf/compatibility_matrix.device.xml, but there is no corresponding .hal definition associated with a hidl_interface module in this build. Typo?
```

Change-Id: Iba290ff6eb649aeb1c521bc502f746aa2c55111f